//
//  ProductDetailWorker.swift
//  Z_VIP
//
//  Created by Danh Dang on 11/29/17.
//  Copyright (c) 2017 com.zalora. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ProductDetailWorker {
    func fetchImageList(for product: Product, _ callback: @escaping (Result<String>)->Void) {
        ServiceManager.product.loadProductImage { (result) in
            callback(result)
        }
    }
}
