//
//  ProductDetailPresenter.swift
//  Z_VIP
//
//  Created by Danh Dang on 11/29/17.
//  Copyright (c) 2017 com.zalora. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductDetailPresentationLogic {
    func present(response: ProductDetail.Response)
}

class ProductDetailPresenter: ProductDetailPresentationLogic {
    weak var viewController: ProductDetailDisplayLogic?
    
    // MARK: Do something
    
    func present(response: ProductDetail.Response) {
        let product = response.product
        var displayProduct = ProductDetail.ViewModel.DisplayProduct()
        displayProduct.name = product.name
        displayProduct.brand = product.brand
        displayProduct.price = "$ \(product.price)"
        let viewModel = ProductDetail.ViewModel(product: displayProduct, imageList: response.imageList)
        viewController?.display(productDetail: viewModel)
    }
}
