//
//  ProductDetailRouter.swift
//  Z_VIP
//
//  Created by Danh Dang on 11/29/17.
//  Copyright (c) 2017 com.zalora. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ProductDetailRoutingLogic {
    func routeToProductDescription()
}

protocol ProductDetailDataPassing {
    var dataStore: ProductDetailDataStore? { get set }
}

class ProductDetailRouter: NSObject, ProductDetailRoutingLogic, ProductDetailDataPassing {
    weak var viewController: ProductDetailViewController?
    var dataStore: ProductDetailDataStore?
    
    func routeToProductDescription() {
        guard let dataStore = dataStore else {
            return 
        }
        
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        guard let productDescriptionVC = storyboard.instantiateViewController(withIdentifier : "ProductDescriptionViewController") as? ProductDescriptionViewController else {
            return
        }
        
        productDescriptionVC.router?.dataStore?.product = dataStore.product
        viewController?.navigationController?.pushViewController(productDescriptionVC, animated: true)
    }
}
