//
//  ProductDetailModels.swift
//  Z_VIP
//
//  Created by Danh Dang on 11/29/17.
//  Copyright (c) 2017 com.zalora. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ProductDetail {
    // MARK: Use cases
    
    
    struct Request {
        var product: Product
    }
    struct Response {
        var product: Product
        var imageList: [String]
    }
    struct ViewModel {
        struct DisplayProduct {
            var name: String
            var brand: String
            var price: String
            
            init() {
                name = ""
                brand = ""
                price = ""
            }
        }
        
        var product: DisplayProduct
        var imageList: [String]
    }
}
