//
//  CatalogWorkerTests.swift
//  Z_VIP
//
//  Created by Danh Dang on 11/30/17.
//  Copyright (c) 2017 com.zalora. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Z_VIP
import XCTest

class CatalogWorkerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: CatalogWorker!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupCatalogWorker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupCatalogWorker() {
        sut = CatalogWorker()
    }
    
    // MARK: Test doubles
    
    // MARK: Tests
    
    func testFetchProducts() {
        let expect = expectation(description: "Fetch products should load 27 products from json")
        sut.fetchProduct { (result) in
            switch result {
            case .success(let products):
                if products.count == 27 {
                    expect.fulfill()
                }
            case .failure(let message):
                print(message)
            }
        }
        
        waitForExpectations(timeout: 1) { (error) in
            if let error = error {
                print(error)
            }
        }
    }
}
