//
//  ProductDescriptionPresenterTests.swift
//  Z_VIP
//
//  Created by Danh Dang on 12/1/17.
//  Copyright (c) 2017 com.zalora. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Z_VIP
import XCTest

class ProductDescriptionPresenterTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: ProductDescriptionPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupProductDescriptionPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupProductDescriptionPresenter() {
        sut = ProductDescriptionPresenter()
    }
    
    // MARK: Test doubles
    
    class ProductDescriptionDisplayLogicSpy: ProductDescriptionDisplayLogic {
        var displayProductDescriptionCalled = false
        func displayProductDescription(_ viewModel: ProductDescription.ViewModel) {
            displayProductDescriptionCalled = true
        }
    }
    
    // MARK: Tests
    
    func testPresentProductDescription() {
        // Given
        let spy = ProductDescriptionDisplayLogicSpy()
        sut.viewController = spy
        let response = ProductDescription.Response(rawString: "")
        
        // When
        sut.present(productDescription: response)
        
        // Then
        XCTAssertTrue(spy.displayProductDescriptionCalled, "present(productDescription:) should ask view controller to display result")
    }
}
