//
//  ProductDescriptionRouter.swift
//  Z_VIP
//
//  Created by Danh Dang on 11/30/17.
//  Copyright (c) 2017 com.zalora. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ProductDescriptionRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ProductDescriptionDataPassing {
    var dataStore: ProductDescriptionDataStore? { get set }
}

class ProductDescriptionRouter: NSObject, ProductDescriptionRoutingLogic, ProductDescriptionDataPassing {
    weak var viewController: ProductDescriptionViewController?
    var dataStore: ProductDescriptionDataStore?
    
    // MARK: Routing
    
}
