//
//  ProductDescriptionPresenter.swift
//  Z_VIP
//
//  Created by Danh Dang on 11/30/17.
//  Copyright (c) 2017 com.zalora. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductDescriptionPresentationLogic {
    func present(productDescription: ProductDescription.Response)
}

class ProductDescriptionPresenter: ProductDescriptionPresentationLogic {
    weak var viewController: ProductDescriptionDisplayLogic?
    
    // MARK: Do something
    func present(productDescription: ProductDescription.Response) {
        let htmlData = productDescription.rawString.data(using: .utf8) ?? Data()
        let options = [NSAttributedString.DocumentReadingOptionKey.documentType: NSAttributedString.DocumentType.html]
        let attributedString = try? NSAttributedString(data: htmlData, options: options, documentAttributes: nil)
        viewController?.displayProductDescription(ProductDescription.ViewModel(attributedString: attributedString ?? NSAttributedString()))
    }
}
