//
//  ProductDescriptionInteractor.swift
//  Z_VIP
//
//  Created by Danh Dang on 11/30/17.
//  Copyright (c) 2017 com.zalora. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductDescriptionBusinessLogic {
    func fetchProductDescription()
}

protocol ProductDescriptionDataStore {
    var product: Product { get set }
}

class ProductDescriptionInteractor: ProductDescriptionBusinessLogic, ProductDescriptionDataStore {
    var presenter: ProductDescriptionPresentationLogic?
    var worker: ProductDescriptionProtocol = ProductDescriptionWorker()
    var product = Product()
    
    // MARK: Do something
    
    func fetchProductDescription() {
        worker.fetchProductDescription(for: product, { (result) in
            switch result {
            case .success(let description):
                self.presenter?.present(productDescription: ProductDescription.Response(rawString: description))
            case .failure(let errorMessage):
                print(errorMessage)
            }
        })
    }
}
