//
//  ProductDetailInteractorTests.swift
//  Z_VIP
//
//  Created by Danh Dang on 11/30/17.
//  Copyright (c) 2017 com.zalora. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Z_VIP
import XCTest

class ProductDetailInteractorTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: ProductDetailInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupProductDetailInteractor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupProductDetailInteractor() {
        sut = ProductDetailInteractor()
    }
    
    // MARK: Test doubles
    
    class ProductDetailPresentationLogicSpy: ProductDetailPresentationLogic {
        var isPresentResponseCalled = false
        
        func present(response: ProductDetail.Response){
            isPresentResponseCalled = true
        }
    }
    
    class ProductDetailWorkerSpy: ProductDetailWorker {
        var isFetchImageListCalled = false
        override func fetchImageList(for product: Product, _ callback: @escaping (Result<String>) -> Void) {
            isFetchImageListCalled = true
            callback(Result.success([]))
        }
    }
    
    // MARK: Tests
    
    func testFetchImageList() {
        // Given
        let presenterSpy = ProductDetailPresentationLogicSpy()
        sut.presenter = presenterSpy
        let workerSpy = ProductDetailWorkerSpy()
        sut.worker = workerSpy
        let request = ProductDetail.Request(product: Product())
        
        // When
        sut.fetchImageList(for: request)
        
        // Then
        XCTAssertTrue(presenterSpy.isPresentResponseCalled, "fetchImageList(for:) should ask the presenter to format the result")
        XCTAssertTrue(workerSpy.isFetchImageListCalled, "fetchImageList(for:) should ask worker to fetch image list")
    }
}
