//
//  ProductDetailWorkerTests.swift
//  Z_VIP
//
//  Created by Danh Dang on 11/30/17.
//  Copyright (c) 2017 com.zalora. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Z_VIP
import XCTest

class ProductDetailWorkerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: ProductDetailWorker!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupProductDetailWorker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupProductDetailWorker() {
        sut = ProductDetailWorker()
    }
    
    // MARK: Test doubles
    
    // MARK: Tests
    
    func testSomething() {
        // Given
        
        // When
        
        // Then
    }
}
