//
//  ProductDetailWorkerTests.swift
//  Z_VIP
//
//  Created by Danh Dang on 11/30/17.
//  Copyright (c) 2017 com.zalora. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Z_VIP
import XCTest

class ProductDetailWorkerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: ProductDetailWorker!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupProductDetailWorker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupProductDetailWorker() {
        sut = ProductDetailWorker(productService: MockProductService())
    }
    
    // MARK: Test doubles
    
    // MARK: Tests
    
    func testFetchProductListSuccess() {
        //Given
        let expect = expectation(description: "ProductDetail worker should successfully return product list")
        var resultImageList: [String] = []
        //When
        sut.fetchImageList(for: MockModels.product1) { (result) in
            switch result {
            case .success(let imageList):
                resultImageList = imageList
                expect.fulfill()
            case .failure(_):
                break
            }
        }
        
        //Then
        waitForExpectations(timeout: 1) { (error) in
            if let error = error {
                print(error)
            }
        }
        XCTAssertEqual(resultImageList, MockProductService.mockImageList, "fetchImageList(for:) should return correct image list data from service")
    }
    
    func testFetchProductFailure() {
        //Given
        let expect = expectation(description: "ProductDetail worker should return failure when service cannot load imagelist")
        sut.productService = MockProductService(shouldReturnFailure: true)
        //When
        sut.fetchImageList(for: MockModels.product1) { (result) in
            switch result {
            case .success(_):
                break
            case .failure(_):
                expect.fulfill()
            }
        }
        
        //Then
        waitForExpectations(timeout: 1) { (error) in
            if let error = error {
                print(error)
            }
        }
    }
}
