//
//  ProductDetailPresenterTests.swift
//  Z_VIP
//
//  Created by Danh Dang on 11/30/17.
//  Copyright (c) 2017 com.zalora. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Z_VIP
import XCTest

class ProductDetailPresenterTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: ProductDetailPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupProductDetailPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupProductDetailPresenter() {
        sut = ProductDetailPresenter()
    }
    
    // MARK: Test doubles
    
    class ProductDetailDisplayLogicSpy: ProductDetailDisplayLogic {
        
        var displayProductDetailCalled = false
        
        func display(productDetail product: ProductDetail.ViewModel) {
            displayProductDetailCalled = true
        }
    }
    
    // MARK: Tests
    
    func testPresentProductDetail() {
        // Given
        let spy = ProductDetailDisplayLogicSpy()
        sut.viewController = spy
        let response = ProductDetail.Response(product: Product(), imageList: [])
        
        // When
        sut.present(response: response)
        
        // Then
        XCTAssertTrue(spy.displayProductDetailCalled, "present(response:) should ask the view controller to display the result")
    }
}
