//
//  CatalogPresenter.swift
//  Z_VIP
//
//  Created by Danh Dang on 11/29/17.
//  Copyright (c) 2017 com.zalora. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CatalogPresentationLogic {
    func present(products: Catalog.Response)
    func present(error: Error)
}

class CatalogPresenter: CatalogPresentationLogic {
    weak var viewController: CatalogDisplayLogic?
    
    func present(products: Catalog.Response) {
        let displayedProducts = products.products.map { Catalog.ViewModel.DisplayedProduct(name: $0.name, mainImageUrl: $0.mainImageUrl) }
        viewController?.display(viewModel: Catalog.ViewModel(displayedProducts: displayedProducts))
    }
    
    func present(error: Error) {
        viewController?.display(error: error)
    }
}
