//
//  CatalogPresenter.swift
//  Z_VIP
//
//  Created by Danh Dang on 11/29/17.
//  Copyright (c) 2017 com.zalora. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CatalogPresentationLogic {
    func present(products: Catalog.Products.Response)
    func present(error message: Catalog.Error.Response)
}

class CatalogPresenter: CatalogPresentationLogic {
    weak var viewController: CatalogDisplayLogic?
    
    func present(products: Catalog.Products.Response) {
        let displayedProducts = products.products.map { Catalog.Products.ViewModel.DisplayedProduct(name: $0.name, mainImageUrl: $0.mainImageUrl) }
        viewController?.display(products: Catalog.Products.ViewModel(displayedProducts: displayedProducts))
    }
    
    func present(error message: Catalog.Error.Response) {
        viewController?.display(error: Catalog.Error.ViewModel(errorMessage: message.errorMessage))
    }
    
}
