//
//  CatalogRouter.swift
//  Z_VIP
//
//  Created by Danh Dang on 11/29/17.
//  Copyright (c) 2017 com.zalora. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CatalogRoutingLogic {
    func routeToProductDetail(productAt index: Int)
}

protocol CatalogDataPassing {
  var dataStore: CatalogDataStore? { get }
}

class CatalogRouter: NSObject, CatalogRoutingLogic, CatalogDataPassing {
  weak var viewController: CatalogViewController?
  var dataStore: CatalogDataStore?
    
    func routeToProductDetail(productAt index: Int) {
        guard let dataStore = dataStore,
            index < dataStore.products.count else {
                return
        }
        
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        guard let productDetailVC = storyboard.instantiateViewController(withIdentifier : "ProductDetailViewController") as? ProductDetailViewController else {
            return
        }
        
        let product = dataStore.products[index]
        productDetailVC.router?.dataStore?.product = product
        viewController?.navigationController?.pushViewController(productDetailVC, animated: true)
    }
}
